### ISSUE TITLE
feature request: user defined types

### ISSUE THREAD

**Issue by Bambofy** [Vexu/bog#24]
hello, is there any plans for incorporating facilities which provide the ability to define your own types similar to c++ classes?

**Comment by Vexu** [comment]
It is already possible with `native_val`s. It's not too ergonomic at the moment and not exposed via the C API but you can see an example of it being used in the [`fs` module of the standard library](https://github.com/Vexu/bog/blob/3449ea84a1644ed77de29eed54ec475e9f98311d/src/std/fs.zig).

I haven't written any examples of `std.fs` since it only includes the bare minimum to test the `native_val` system but here's a simple example of using what currently exists:
```julia
let {open} = import "std.fs"

let file = open("foo.txt")
file.write("Hello!")
file.close()
```
